WITH sessions AS (
  SELECT
    *
  FROM
    {{ ref('stg_google_analytics__sessions') }}
),
final AS (
  SELECT
    SESSION_ID,
    FLATTENED_DIMENSIONS.KEY::INTEGER   AS DIMENSION_INDEX,
    FLATTENED_DIMENSIONS.VALUE::VARCHAR AS DIMENSION_VALUE
  FROM
    sessions,
    LATERAL FLATTEN(INPUT => CUSTOM_DIMENSIONS,  recursive => true) FLATTENED_DIMENSIONS
  WHERE
    FLATTENED_DIMENSIONS.KEY IS NOT NULL
)
SELECT
  *
FROM
  final
