name: 'google_analytics_360'
version: '0.0.1'
config-version: 2
require-dbt-version: ">=0.18.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]
