WITH base AS (
  SELECT
    *
  FROM
    {{ source('GOOGLE_ANALYTICS', 'SESSIONS') }}
),
final AS (
  SELECT
    {{ dbt_utils.surrogate_key(['FULLVISITORID', 'VISITID', 'VISITSTARTTIME']) }} AS SESSION_ID,
    FULLVISITORID        AS FULL_VISITOR_ID,
    VISITID              AS VISIT_ID,
    VISITSTARTTIME       AS VISIT_START_TIME,
    DATE                 AS SESSION_DATE,
    CHANNELGROUPING      AS CHANNEL_GROUPING,
    CLIENTID             AS CLIENT_ID,
    CUSTOMDIMENSIONS     AS CUSTOM_DIMENSIONS,
    DEVICE,
    GEONETWORK           AS GEO_NETWORK,
    SOCIALENGAGEMENTTYPE AS SOCIAL_ENGAGEMENT_TYPE,
    TOTALS,
    TRAFFICSOURCE        AS TRAFFIC_SOURCE,
    USERID               AS USER_ID,
    VISITNUMBER          AS VISIT_NUMBER,
    VISITORID            AS VISITOR_ID
  FROM
    base
)
SELECT
  *
FROM
  final
